name: YAML Lint

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
  

jobs:
  validate-yaml:
    name: Validate YAML syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate YAML files
        uses: GrantBirki/json-yaml-validate@v3
        with:
          comment: true     # Adds a PR comment if invalid
          include: ".github/workflows/my-workflow.yml"
          exclude: "**/*.yaml **/*.yml"
          base_dir: "."     # Validate all YAML files in the repo

