name: YAML Lint

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  validate-yaml:
    name: Validate YAML syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate YAML files
        uses: GrantBirki/json-yaml-validate@v3
        with:
          comment: true     # Adds a PR comment if invalid
          base_dir: "."     # Validate all YAML files in the repo

